### ISSUE TITLE
GetColumnsPropertyInfos() missing code

### ISSUE THREAD

**Issue by im1dermike** [verdie-g/StoredProcedureDotNetCore#3]
It looks like the most recent version of this codebase has the `GetProperty()` code commented out in the `GetColumnsPropertyInfos()` method which, at least in my case, resulted in nothing ever mapping.  I fixed it locally, but you may want to address.

**Comment by verdie-g** [comment]
Could you tell me which lines did you fix ? It seems like it's working for me, at least my Program.Main returns the right values.
