### ISSUE TITLE
How to include multiple parameters?

### ISSUE THREAD

**Issue by Phillippe43** [verdie-g/StoredProcedureDotNetCore#4]
This works great with only one parameter, but I can't figure out how to include more than one to work with the DbTool.cs

**Comment by verdie-g** [comment]
ExecuteStoredProcedure takes a variable number of arguments:
```csharp
public static List<T> ExecuteStoredProcedure<T>(this DbContext context, string name, params StoredProcedureParameter[] parameters)
```

You can pass as many arguments a you want:
```csharp
context.ExecuteStoredProcedure<ResultModel>("[dbo].[StoredProcedureName]",
        new StoredProcedureParameter("param_name", value)
        new StoredProcedureParameter("param_name2", value2)
        new StoredProcedureParameter("param_name3", value3)
);
```

**Comment by verdie-g** [comment]
I replaced _StoredProcedureParameter_ by tuples [in my last commit](https://github.com/verdie-g/StoredProcedureDotNetCore/commit/0071ee6d754d81f82206c171dc259f0151a53889), so it's less verbose.

You can pass parameters like that now : 
```csharp
context.ExecuteStoredProcedure<ResultModel>("[dbo].[StoredProcedureName]",
        ("param_name", value),
        ("param_name2", value2),
        ("param_name3", value3)
);
```
